Challenge
codephil-columbia/typephil pull request #68
Opened 2019-01-15 17:27 UTC by mattvanegas13

@francesar > https://www.youtube.com/watch?v=dQw4w9WgXcQ

2019-01-16 00:54 UTC, francesar commented on src/Challenge.js
> +import './style/Challenge.css';
can you order ur imports as 

1. 3rd party code

2. internal code 

3. styles

2019-01-16 00:54 UTC, francesar commented on src/Challenge.js
> +`
make ur amount of whitespace between these two only one line

2019-01-16 00:56 UTC, francesar commented on src/Challenge.js
> +    this.BeginChallenge=this.BeginChallenge.bind(this)
space between the equals ` this.BeginChallenge = this.BeginChallenge.bind(this)`

2019-01-16 00:59 UTC, francesar commented on src/Challenge.js
> +  EzSelected()
use lowerCamel case

2019-01-16 00:59 UTC, francesar commented on src/Challenge.js
> +  {
dont add a line break before the bracket 
` MedSelected() {`

2019-01-16 01:16 UTC, francesar commented on src/Challenge.js
> +    var difficulty="";
dont use `var`, always prefer to use const if you intend the variable to be immutable or `let` if its going to be mutable

2019-01-16 01:20 UTC, francesar commented on src/Challenge.js
> +    if(state.isEzActive == true)
since all the values of `state.isEzActive/isMidActive/isHardActive` are all boolean values, you don't have to `== true`

2019-01-16 01:26 UTC, francesar commented on src/Challenge.js
> +    /*figure out how to carry over difficulty to challenge*/
we can do this through redux, if you look at `src/store.js` we use `redux-persist` to save things within the web browser across page refreshes. you could persist the difficulty through there and retrieve it once we render the next page. we can talk about options to do this, since theres more than one way

2019-01-16 01:27 UTC, francesar commented on src/Challenge.js
> +const mapDispatchToProps = dispatch => {
you might not need these yet (`mapDispatchToProps` & `mapStateToProps`)

2019-01-16 02:48 UTC, francesar commented on src/CocoType.js
> +          <div className="MetaWrapper">
lower camel case for style names

2019-01-16 02:50 UTC, francesar commented on src/DifficultyTab.js
> +    this.state={
include space between 
`
this.state = {
exChose: false
...
`

2019-01-16 02:50 UTC, francesar commented on src/DifficultyTab.js
> +      {
put this on the same line as `this.setState({`

2019-01-16 02:51 UTC, francesar commented on src/DifficultyTab.js
> +  ezEnabled(){
space `() { `

2019-01-16 02:56 UTC, francesar requested changes
keep this in mind when u code [js style guide](https://github.com/airbnb/javascript )
you def dont have to adhere to it strictly

2019-01-19 07:29 UTC, francesar commented on src/Challenge.js
> +      isEzActive:false,
instead of having state w/ flags for each difficulty selected (ez, mid, hard) might be better to create an enum in the Challenge class with the 3 states using either `Object.freeze` or a normal js object and define a field within state that is called `difficulty` or something
changing the difficulty now means that u only have to edit one field in Challenge's state vs 3

2019-01-19 07:32 UTC, francesar commented on src/DifficultyTab.js
> +      return (
use 2 space tabs vs 4

2019-03-30 01:30 UTC, mattvanegas13 commented
@francesar

2019-04-03 23:51 UTC, closed without merging